Projects/TelegramEchoBot/.env.sample, Projects/TelegramEchoBot/README.md, Projects/TelegramEchoBot/bot.py, Projects/TelegramEchoBot/requirements.txt
=> Add a simple telegram echo-bot

Projects/GuessNumber/guess_number.py
=> guess a number game

Projects/Simple-calculator/.gitattributes, Projects/Simple-calculator/.gitignore, Projects/Simple-calculator/README.md, Projects/Simple-calculator/main.py
Here is my beginner-level python project.
It is a calculator with GUI, made using tkinter.
=> simple calculator using tkinter

Projects/Website_Url_Detector/README.md, Projects/Website_Url_Detector/detect_urls.py, Projects/Website_Url_Detector/requirements.txt
Adding a script that detects and extracts all the URL links on a given website
=> Add website url detector

Projects/Name_Detector/README.md, Projects/Name_Detector/detect_names.py, Projects/Name_Detector/requirements.txt, Projects/Name_Detector/test_file.txt
Adding a script that detects people's names in a given text.
=> Add name detector

README.md
=> updated contributors section in main readme 

Projects/Google_Selenium_Searcher/Google_Search.py
Used this code in a project for some work hope this helps
=> Added a google scraper using python

Projects/GUI_calendar/GUI_calendar_generator.py
I have added a simple GUI calendar created with tkinter in python.
=> add GUI calendar

Projects/AreaFinder/AreaFinder4,2dShapes.py
2d shapes like square, rectangle, triangle, and circle
i've tried and tested them and they work perfectly when compared with googles calculator
we just need to add a loop for not accedently putting an alphabet in the number insertion place
=> Created a program which finds the area of 4 specific 2d shapes

Projects/Ascii_art/Readme.md, Projects/Ascii_art/ascii_art.py, Projects/Ascii_art/requirements.txt
A simple image to ascii art generator in python.
=> ascii_art_generator

speedtest.py
The file is a program written in python to run a speed-test to measure internet speed.
=> adding speedtest.py

Projects/linearEquation.py
Added python script which can solve linear equation
=> Added python script which can solve linear equation

Projects/Pascal Triangle/Pascal_triangle.py, Projects/Pascal_triangle.py
This Program generates a pascal triangle of n generated rows.
=> Created Pascal_triangle.py

Projects/Palindromify List/PalindromifyList.py
This python program finds next palindrome of integers given in list.
=> Created Palindromify list folder

Anagram Game/Sourodip20kar.md
=> Anagram Game issue #58

Projects/Ai Model/README.md, Projects/Ai Model/dockerfile, Projects/Ai Model/main.py, Projects/Ai Model/requirements.txt
* Added a project of ai model deployment flask for any environment due to docker
* it will help new learners to deploy ai model on any environment
=> AI modal flask deployment with docker

Projects/BMI_Calculator.py/Readme.md, Projects/BMI_Calculator.py/main.py
I have added my python project, kindly review and merge it.
=> New BMI Calculator

README.md
=> Beautified the main readme with maintainers details and labels

Projects/BlackjackGame/blackjack.py
Pull Request associated with Issue https://github.com/Arindam200/Python_Projects/issues/89
=> Added Blackjack Game in Python Projects folder

Projects/insta profile pic downloader.py, Projects/voice_assisstant.py
I made a voice assistant using pyautogui, speech_recognition and pyttsx3. 
It is capable of performing basic tasks such as decreasing the volume or increasing the volume, etc etc
=> Voice Assistant program made by me

Projects/Algorithms/InsertionSort.py
I added Added InsertionSort.py to Algorithms folder.
=> Added InsertionSort.py to Algorithms folder

Projects/Algorithms/SelectionSort.py
I added Added SelectionSort.py to Algorithms folder.
=> Added SelectionSort.py to Algorithms folder

Projects/Algorithms/ShellSort.py
I added Added ShellSort.py to Algorithms folder.
=> Added ShellSort.py to Algorithms folder

Projects/Algorithms/BubbleSort.py
I added Added BubbleSort.py to Algorithms folder.
=> Added BubbleSort.py to Algorithms folder

Projects/MathGame/SimpleProduct.py
=> Added a Math Game

Projects/MathGame/AgeInDay.py
=> Added age in days game

Projects/Linear_search.py
=> LInear Search

Projects/rock-paper-scissors/RPS.py
=> Add Game Loop For RPS

Projects/Body_Tracking/Readme.txt, Projects/Body_Tracking/main.py
This project can be used to play Subway surfers or any other runner games using physical body movements.
=> Added Body Tracking using opencv and mediapipe

Projects/Web-Crawler/README.md, Projects/Web-Crawler/demo.py, Projects/Web-Crawler/domain.py, Projects/Web-Crawler/link_finder.py, Projects/Web-Crawler/main.py, Projects/Web-Crawler/spider.py
<i> Program by : Swayamshree Mohanty  
A Web crawler, sometimes called a spider or spiderbot and often shortened to crawler, is an Internet bot that systematically browses the World Wide Web, typically operated by search engines for the purpose of Web indexing (web spidering). In this project, using Python, a Web-Crawler is created that fetches all the links from a particular website. (Use VS Code or PyCharm for getting the desired output). </i>
=> Web Crawler

Leetcode_Solutions/Median of Two sorted arrays/README.md, Leetcode_Solutions/Median of Two sorted arrays/solution.cpp
Under issue #115.
Added leetcode Hard question: Finding a median of two sorted arrays question code in cpp.
[https://leetcode.com/problems/median-of-two-sorted-arrays/](url)
=> Added Median_of_two_sorted_arrays leetcode code #115

Leetcode_Solutions/Valid Sudoku/README.md, Leetcode_Solutions/Valid Sudoku/solution.py
Checking if a 9 x 9 Sudoku board is valid. Only the filled cells need to be validated according to the following rules:
Each row must contain the digits 1-9 without repetition.
Each column must contain the digits 1-9 without repetition.
Each of the nine 3 x 3 sub-boxes of the grid must contain the digits 1-9 without repetition.
=> Added python code for checking valid paranthesis

Projects/QR Code Generator/qr_generator.py
Added QR code generator project.
=> Added Project

Projects/text_cleaner/README.md, Projects/text_cleaner/remove_punctuation_numbers.py
Adding a project with a Python script that cleans an input text, removing punctuation and numbers.
=> Add text cleaner project

Leetcode_Solutions/Longest Common Prefix #14/solution.py
Added a function to find the longest common prefix string amongst an array of strings.
If there is no common prefix, function returns an empty string "".
=> Adding python code to find longest common prefix

Leetcode_Solutions/Palindrome Number #9/README.md, Leetcode_Solutions/Palindrome Number #9/Solution.py
Hey, @Arindam200 I have added a Leetcode solution please review and merge it.
thank you
=> Added Leetcode Problem Solution

Leetcode_Solutions/Happy Number #202/README.md, Leetcode_Solutions/Happy Number #202/Solution.py
@Arindam200 Added another leetcode solution, hope the contribution helps, please review and merge
=> Added another Leetcode Solution No 202

Leetcode_Solutions/Letter Combinations of a Phone Number/Letter Combinations of a Phone Number.py, Leetcode_Solutions/Letter Combinations of a Phone Number/readme.md
Give it a check, I hope it's upto your requirements.
=> Letter Combinations of a Phone Number

Leetcode_Solutions/3sumCloset/3sum_closet.py
Find three integers in nums array such that the sum is closest to target.
=> Created a new file 3sum_closet.py

Leetcode_Solutions/4SUM/4_SUM.py, Leetcode_Solutions/RomanToInteger/Roman_to_integer.py
Given a roman numeral, convert it to an integer.
=> Created a new file Roman_to_integer.py

Leetcode_Solutions/Breaking a Palindrome/breaking_a_palindrome.cpp, Leetcode_Solutions/Breaking a Palindrome/readme.md
Plz Merge it and add hacktoberfest label.
=> Add Leetcode Solution for Breaking a Palindrome

Leetcode_Solutions/Roman to Integer #13/README.md, Leetcode_Solutions/Roman to Integer #13/Solution.py, gitartwork.svg
@Arindam200 Kindly Review and merge.
Thank You.
=> Added Solution to a new Leetcode Problem

Projects/MathGame/sayuni1.py, Projects/MathGame/sayuni3.py
I added a python file to convert "Zero" to 0 and "One" to 1
=> Convert "Zero" to 0 and "One" to 1

Leetcode_Solutions/KadaneAlgo/Kadane_Algorithm.py, Leetcode_Solutions/Pascal's Triangle/Pascal_triangle.py
Given an array my_array[] of size array_size . The task is to find the sum of the contiguous subarray within a arr[] with the largest sum.
=> Created a new file Kadane_Algorithm.py

Leetcode_Solutions/NEXT PERMUTATION/NEXT_Permutation.py
Given an array of integers nums, find the next permutation of nums.
=> Created a new file NEXT_Permutation.py

Projects/rock-paper-scissors/RPS.py
=> Added Scores And a Bit of Refactoring on RPS

gitartwork.svg
Reverts Arindam200/Python_Projects#162
=> Revert "Create  Median of Two Sorted Array.py"

Projects/MathGame/sayuni4.py
I added a python file to find the smallest and the biggest number
=> Added a python file

Projects/MathGame/challenge6_sayuni.py
I added a python file to convert seconds to hours, minutes, and seconds.
=> Add a python file

Projects/Python Game
=> Create Python Stone/Paper/Scissor Game

Leetcode_Solutions/Subsets
Given an integer array nums of unique elements, return all possible subsets (the power set).
The solution set must not contain duplicate subsets. Return the solution in any order.
=> Added Subsets.cpp
